export const STATUS_CODE = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
};

const muscleGroups = {
  abductors: 'abdutores',
  adductors: 'adutores',
  cardiovascular_system: 'sistema cardiovascular',
  delts: 'deltoides',
  glutes: 'glúteos',
  lats: 'dorsais',
  levator_scapulae: 'elevador da escápula',
  pectorals: 'peitorais',
  quads: 'quadríceps',
  serratus_anterior: 'serrátil anterior',
  spine: 'coluna vertebral',
  upper_back: 'parte superior das costas',
  neck: 'pescoço',
  trapezius: 'trapézio',
  back: 'costas',
  erector_spinae: 'eretor da espinha',
  biceps: 'bíceps',
  triceps: 'tríceps',
  forearm: 'antebraço',
  abs_core: 'abdômen/core',
  leg: 'perna',
  calf: 'panturrilha',
  hips: 'quadris',
  cardio: 'cardio',
  full_body: 'full body',
} as const;

type tMuscleGroups = keyof typeof muscleGroups;

const equipments = {
  assisted: 'assistido',
  band: 'faixa',
  barbell: 'barra',
  body_weight: 'peso corporal',
  bosu_ball: 'bola bosu',
  cable: 'cabo',
  dumbbell: 'halter',
  elliptical_machine: 'máquina elíptica',
  ez_barbell: 'barra w',
  hammer: 'martelo',
  kettlebell: 'kettlebell',
  leverage_machine: 'máquina de alavanca',
  medicine_ball: 'bola medicinal',
  olympic_barbell: 'barra olímpica',
  resistance_band: 'faixa de resistência',
  roller: 'rolo',
  rope: 'corda',
  skierg_machine: 'máquina skierg',
  sled_machine: 'máquina de trenó',
  smith_machine: 'máquina smith',
  stability_ball: 'bola de estabilidade',
  stationary_bike: 'bicicleta estacionária',
  stepmill_machine: 'máquina de escada',
  tire: 'pneu',
  trap_bar: 'barra hexagonal',
  upper_body_ergometer: 'ergômetro de parte superior do corpo',
  weighted: 'com peso',
  wheel_roller: 'rolo de roda',
} as const;

type tEquipment = keyof typeof equipments;
